const { Router } = require('express');
const userModel = require("../models");
const { GoogleSpreadsheet } = require('google-spreadsheet');
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const router = Router();
const auth = require("../middleware/auth");

router.get("/welcome", auth, (req, res) => {
  res.status(200).send("Welcome 🙌 ");
});


//Raiz
router.get('/', (req, res) => {
  res.json(
    {
      "Title": "Hola mundo usando rutas!"
    }
  );
})

//Google Sheet
router.get('/customer', async (req, res) => {

  // Initialize the sheet - doc ID is the long id in the sheets URL
  const doc = new GoogleSpreadsheet('1sdgAH9zQo9OYhzw4VjQWAvm3o5-OXX5G2Et1tm4E0j0');

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || 'holding@holding-346100.iam.gserviceaccount.com',
    private_key: process.env.GOOGLE_PRIVATE_KEY,
  });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
  // await doc.updateProperties({ title: 'renamed doc' });

  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  console.log(sheet.title);
  console.log(sheet.rowCount);

  // read rows
  const rows = await sheet.getRows(); // can pass in { limit, offset }
  console.log(rows[0].ID);
  console.log(rows[0].firstName);


  const sheet1 = doc.sheetsByIndex[1]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  console.log(sheet1.title);
  console.log(sheet1.rowCount);

  // adding / removing sheets
  //const newSheet = await doc.addSheet({ title: 'hot new sheet!' });
  //await newSheet.delete();


  res.json(
    {
      "Title": doc.title
    }
  );
})


router.post("/add_user", async (request, response) => {
  const user = new userModel(request.body);

  try {
    await user.save();
    response.send(user);
  } catch (error) {
    response.status(500).send(error);
  }
});

router.post("/login", async (req, res) => {

  // Our login logic starts here
  try {
    // Get user input
    const { email, password } = req.body;

    // Validate user input
    if (!(email && password)) {
      res.status(400).send("All input is required");
    }
    // Validate if user exist in our database
    //const user = await User.findOne({ email });

    // Initialize the sheet - doc ID is the long id in the sheets URL
    const doc = new GoogleSpreadsheet('1sdgAH9zQo9OYhzw4VjQWAvm3o5-OXX5G2Et1tm4E0j0');

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || 'holding@holding-346100.iam.gserviceaccount.com',
      private_key: process.env.GOOGLE_PRIVATE_KEY,
    });

    await doc.loadInfo(); // loads document properties and worksheets
    //console.log(doc.title);
    // await doc.updateProperties({ title: 'renamed doc' });

    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    // read rows
    const rows = await sheet.getRows({ limit: 100, offset: 0 }); // can pass in { limit, offset }
    let bFound = false;
    let user = { _id: "", token: "", firstName:"", password:"" };
    let rowCount = rows.length;
    for (let i = 0; i < rowCount; i++) {
      if (rows[i].email == email) {
          bFound = true;
          user._id = rows[i].ID;
          user.password = rows[i].key;
          user.firstName = rows[i].firstName
          break;
      }
    }

    console.log("pass:", await bcrypt.hash(password, 10));
    if (bFound && (await bcrypt.compare(password, user.password))) {
      // Create token
      const token = jwt.sign(
        { user_id: user._id, email },
        process.env.TOKEN_KEY,
        {
          expiresIn: "2h",
        }
      );

      // save user token
      user.token = token;

      // user
      res.status(200).json(user);
    }
    res.status(400).send("Invalid Credentials");
  } catch (err) {
    console.log(err);
  }
  // Our register logic ends here
});


router.post("/register", async (req, res) => {
  // Our register logic starts here
  try {
    // Get user input
    const { first_name, last_name, email, password } = req.body;


    console.log(req.body);
    console.log(first_name, last_name, email, password);

    // Validate user input
    if (!(email && password && first_name && last_name)) {
      res.status(400).send("All input is required");
    }

    // check if user already exist
    // Validate if user exist in our database
    //const oldUser = await User.findOne({ email });

    // Initialize the sheet - doc ID is the long id in the sheets URL
    const doc = new GoogleSpreadsheet('1sdgAH9zQo9OYhzw4VjQWAvm3o5-OXX5G2Et1tm4E0j0');

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || 'holding@holding-346100.iam.gserviceaccount.com',
      private_key: process.env.GOOGLE_PRIVATE_KEY,
    });

    await doc.loadInfo(); // loads document properties and worksheets
    //console.log(doc.title);
    // await doc.updateProperties({ title: 'renamed doc' });

    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    console.log(sheet.title);
    console.log(sheet.rowCount);

    // read rows
    const rows = await sheet.getRows({ limit: 100, offset: 0 }); // can pass in { limit, offset }
    console.log(rows[0].ID);
    console.log(rows[0].firstName);

    console.log(rows);
    console.log(rows.length);

    let bFound = false;
    let user = { _id: "", token: "" };
    let rowCount = rows.length;
    for (let i = 0; i < rowCount; i++) {
      console.log(rows[i].ID.valueType);

      if (rows[i].ID === undefined) {
        break;
      }
      else {
        let emailhc = rows[i].email;
        console.log("correo:", emailhc);
        console.log("correo:", email);
        if (emailhc == email) {
          bFound = true;
          user._id = rows[i].ID;
          break;
        }
        console.log(rows[i].ID);
        console.log(rows[i].firstName);
        console.log(rows[i].email);
      }
    }
    /*const sheet1 = doc.sheetsByIndex[1]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    console.log(sheet1.title);
    console.log(sheet1.rowCount);*/

    // adding / removing sheets
    //const newSheet = await doc.addSheet({ title: 'hot new sheet!' });
    //await newSheet.delete();



    if (bFound) {
      return res.status(409).send("User Already Exist. Please Login");
    }

    //Encrypt user password
    let encryptedPassword = await bcrypt.hash(password, 10);

    /* // Create user in our database
    const user = await User.create({
      first_name,
      last_name,
      email: email.toLowerCase(), // sanitize: convert email to lowercase
      password: encryptedPassword,
    }); */

    // Create token
    const token = jwt.sign(
      { user_id: user._id, email },
      process.env.TOKEN_KEY,
      {
        expiresIn: "2h",
      }
    );
    // save user token
    user.token = token;

    // return new user
    res.status(201).json(user);
  } catch (err) {
    console.log(err);
  }
  // Our register logic ends here
});


module.exports = router;